name: deploy

on: push

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
        continue-on-error: true
      - name: Build
        run: npm run build --if-present
        continue-on-error: true
      - name: Heroku login credentials
        run: |
          cat << EOF > .netrc
            machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
            machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
      - name: Add Heroku remote
        run: heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Push to Heroku
        run: git push heroku master
