name: Deploy

on:
  push:

    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      continue-on-error: true
    - run: npm run build --if-present
      continue-on-error: true
    - uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "rest-api-resume"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        healthcheck: "https://rest-api-resume.herokuapp.com"
        branch: master
        procfile: "web: npm start"
